In [1]:
import math
import numpy
from numpy import linalg

In [20]:
#Given three points
p1 = numpy.array([[2],[2]])
p2 = numpy.array([[0],[0]])
p3 = numpy.array([[-2],[-2]])
N = 3
p1.shape

(2, 1)

In [3]:
#calculate mean for both x and y directions
Mean = (1/N)*(p1+p2+p3)
Mean

array([[0.],
       [0.]])

In [4]:
#calculate covariances
Cov_x_y = (p1[0]*p1[1] + p2[0]*p2[1] + p3[0]*p3[1])/(N-1)
Cov_y_x = Cov_x_y

Cov_y_x

array([4.])

In [5]:
#calculate variances
Var_x = ((p1[0] - Mean[0])**2 + (p2[0] - Mean[0])**2 + (p3[0] - Mean[0])**2)/(N-1)

Var_x

array([4.])

In [6]:
Var_y = ((p1[1] - Mean[1])**2 + (p2[1] - Mean[1])**2 + (p3[1] - Mean[1])**2)/(N-1)

Var_y

array([4.])

In [7]:
#create covariance matrix

Cov_m = numpy.array([[Var_x[0], Cov_x_y[0]],[Cov_y_x[0], Var_y[0]]])
Cov_m

array([[4., 4.],
       [4., 4.]])

In [8]:
#find the eigenvalues and corresponding eigenvectors for the covariance matrix
#symmetric matrix of covariance matrix
sym_cov1 = numpy.matmul(numpy.transpose(Cov_m),Cov_m)
w1, v = linalg.eig(sym_cov1)
w1  = numpy.sqrt(numpy.round(numpy.diag(w1),2))
w1 # the eigenvalues matrix

array([[8., 0.],
       [0., 0.]])

In [13]:
v #the orthogonal matrix v for symmetric matrix
v_transpose = numpy.transpose(v)
v_transpose

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [16]:
#find symmetric matrix of covariance matrix
sym_cov2 = numpy.matmul(Cov_m,numpy.transpose(Cov_m))
w2, u = linalg.eig(sym_cov2)
u #another orthogonal matrix u for symmetric matrix

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [18]:
#compute first pc
pc1 = u[:,0]*w1[0,0]*v_transpose[0,:]
pc1

array([4., 4.])

In [21]:
s1 = numpy.dot(pc1,p1)
s1

array([16.])

In [23]:
s2 = numpy.dot(pc1,p2)
s2

array([0.])

In [24]:
s3 = numpy.dot(pc1,p3)
s3

array([-16.])

In [26]:
#new variance after projection

new_var = numpy.matmul(numpy.transpose(pc1),numpy.matmul(Cov_m,pc1))
new_var

255.99999999999994